/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controle.ProdutosControle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MoClientes;
import model.MoProdutos;

/**
 *
 * @author suporte11-pc
 */
public class BuscaProduto extends javax.swing.JDialog {

    ProdutosControle controle = new ProdutosControle();
    private String DescSelecionado, PrecoSelecionado, ProdIdSelecionado, unidMedSelecionado;
    private Double precoIntSelecionado;
    
    /**
     * Creates new form BuscaProduto
     */
    public BuscaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaProdutoJdailog();
    }
     public void carregaProdutoJdailog() {

        DefaultTableModel modelo = (DefaultTableModel) getjTableBuscaProduto().getModel();
        for (MoProdutos prod : controle.carregaProd()) {

            modelo.addRow(new Object[]{prod.getId(), prod.getDescricao(), prod.getUnid_medida(),prod.getPreco_venda()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBuscaProduto = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();
        jButtonSelecionado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableBuscaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descricao", "Unid Med", "P Unit"
            }
        ));
        jScrollPane1.setViewportView(jTableBuscaProduto);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonSelecionado.setText("Selecionado");
        jButtonSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSelecionado)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonSair)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSelecionado)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionadoActionPerformed
        int linha = getjTableBuscaProduto().getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente");
        } else {

            // setSelecionado(true);
            setProdIdSelecionado(getjTableBuscaProduto().getValueAt(linha, 0).toString());
            setDescSelecionado(getjTableBuscaProduto().getValueAt(linha, 1).toString());
            setUnidMedSelecionado(getjTableBuscaProduto().getValueAt(linha, 2).toString());
            setPrecoSelecionado(getjTableBuscaProduto().getValueAt(linha, 3).toString());
            this.dispose();

        }
    }//GEN-LAST:event_jButtonSelecionadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaProduto dialog = new BuscaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSelecionado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBuscaProduto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the DescSelecionado
     */
    public String getDescSelecionado() {
        return DescSelecionado;
    }

    /**
     * @param DescSelecionado the DescSelecionado to set
     */
    public void setDescSelecionado(String DescSelecionado) {
        this.DescSelecionado = DescSelecionado;
    }

    /**
     * @return the PrecoSelecionado
     */
    public String getPrecoSelecionado() {
        return PrecoSelecionado;
    }

    /**
     * @param PrecoSelecionado the PrecoSelecionado to set
     */
    public void setPrecoSelecionado(String PrecoSelecionado) {
        this.PrecoSelecionado = PrecoSelecionado;
    }

    /**
     * @return the ProdIdSelecionado
     */
    public String getProdIdSelecionado() {
        return ProdIdSelecionado;
    }

    /**
     * @param ProdIdSelecionado the ProdIdSelecionado to set
     */
    public void setProdIdSelecionado(String ProdIdSelecionado) {
        this.ProdIdSelecionado = ProdIdSelecionado;
    }

    /**
     * @return the jTableBuscaProduto
     */
    public javax.swing.JTable getjTableBuscaProduto() {
        return jTableBuscaProduto;
    }

    /**
     * @param jTableBuscaProduto the jTableBuscaProduto to set
     */
    public void setjTableBuscaProduto(javax.swing.JTable jTableBuscaProduto) {
        this.jTableBuscaProduto = jTableBuscaProduto;
    }

    /**
     * @return the precoIntSelecionado
     */
    public Double getPrecoIntSelecionado() {
        return precoIntSelecionado;
    }

    /**
     * @param precoIntSelecionado the precoIntSelecionado to set
     */
    public void setPrecoIntSelecionado(Double precoIntSelecionado) {
        this.precoIntSelecionado = precoIntSelecionado;
    }

    /**
     * @return the unidMedSelecionado
     */
    public String getUnidMedSelecionado() {
        return unidMedSelecionado;
    }

    /**
     * @param unidMedSelecionado the unidMedSelecionado to set
     */
    public void setUnidMedSelecionado(String unidMedSelecionado) {
        this.unidMedSelecionado = unidMedSelecionado;
    }
    
    
}
